spring:
  datasource:
    url: jdbc:mysql://localhost:3306/myblog1?serverTimezone=UTC
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
logging:
  level:
    root: info
    com.pony: debug
  file:
    path: log/myblog1.log


